version: '3.8'
services:
  backend:
    image: python:3.9
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
